### ISSUE TITLE
Can we get the documentation for this

### ISSUE THREAD

**Issue by mujaffars** [becvert/cordova-plugin-admob-mediation-facebook#1]
Need to have an example documentation for actual implementation

**Comment by becvert** [comment]
All is said in the README:
You install this plugin alongside [admob-free](https://github.com/ratson/cordova-plugin-admob-free) for instance, and you call the javascript API of the latter.
The Admob SDK included with admob-free is in charge of interacting with this Facebook Adapter code.
There's no Javascript API with this plugin. It's just a "drop-in" plugin.

**Comment by mujaffars** [comment]
With phonegap build how to include this in config.xml?

`<gap:plugin name="cordova-plugin-admob-mediation-facebook" source="npm" />` Is this correct?

Is **Facebook Audience Network** sdk required for this while using with phonegap build if yes then how to include it?

Thanks,

**Comment by becvert** [comment]
I'm not familiar with phonegap, but I'd say it should look something like that indeed:
```
<gap:plugin name="cordova-plugin-admob-free" source="npm" />
<gap:plugin name="cordova-plugin-admob-mediation-facebook" source="npm" />
```
You should not need to add the FAN sdk otherwise.

**Comment by mujaffars** [comment]
Hello Becvert

I have tried to implement facebook mediation but it is not working

The google page [sdk less](https://support.google.com/admob/answer/3063564?ctx=tltp&hl=en) says. There are few mediation networks with sdk-free implementation. But in that category Facebook didn't come.

So is sdk really required for this?
