### ISSUE TITLE
iOS app ad request not detected by Facebook

### ISSUE THREAD

**Issue by haydenlak** [becvert/cordova-plugin-admob-mediation-facebook#4]
Hi, I've added the plugin to my cordova project and published for both Android and iOS. I then added the Android and iOS apps to Facebook Audience Network (FAN) and created the placements. I've also added the necessary mediation sources to adMob based on the FAN placement codes.

Facebook managed to detect ad requests for my Android app but not the iOS app. The iOS app is getting requests but somehow, Facebook is not detecting it, so I can't move to the next step and send the iOS app for review.  

![image](https://cloud.githubusercontent.com/assets/28016383/25398625/4b7344de-2a1f-11e7-8cd3-a5ddf6b5f387.png)

![image](https://cloud.githubusercontent.com/assets/28016383/25398603/3d91c91c-2a1f-11e7-965c-1e1dc968116b.png)

Appreciate any help on this. Thank you.

**Comment by becvert** [comment]
are you sure the iOS is getting requests? is the AdMob screenshot iOS only?

**Comment by haydenlak** [comment]
Yes, the AdMob screenshot is for iOS only. This is the screenshot for Android. The impressions are coming in:
![image](https://cloud.githubusercontent.com/assets/28016383/25468111/f3fa4680-2b45-11e7-9d6a-ea1d764fb972.png)

**Comment by becvert** [comment]
My iOS apps in production are reporting impressions. So I think this plugin is working fine for the least

Facebook says that you must generate requests on a real device and an admin, dev or tester must send the first requests. The admin, dev or tester must be logged in with Facebook on that device.
do you match these requirements?

**Comment by becvert** [comment]
any news with this?

**Comment by mattlin4567** [comment]
@becvert Hi, I'm wondering how to test if it's working.
I set admob's ecpm to 100 and audience network as 0.01, 
but audience network didn't show.  
and I tested on iPhone SE, do release or develop version affect?

**Comment by PixelnomadsLtd** [comment]
Same problem here, it worked well on my android app but not on iOS. I can't send an ad request because it shows only Google ads and no Facebook ads on my iOS test device (tested with iPad and iPhone and for sure logged into my facebook account). Admob is also setup correct, same settings like on android... any idea?

**Comment by becvert** [comment]
make sure the eCPM is high for Facebook so it is on top of the mediation list. 

review once again the steps https://developers.google.com/admob/ios/mediation/facebook

**Comment by PixelnomadsLtd** [comment]
My iOS test device generates requests but doesn't display any facebook ad, just google ads. My AdMob settings:
![admob](https://user-images.githubusercontent.com/6918514/30420358-9a0ab56c-9939-11e7-8305-1e89901a29c6.PNG)
My Facebook settings:
![facebook](https://user-images.githubusercontent.com/6918514/30420364-9da02130-9939-11e7-95b4-14069a248085.PNG)
Worked well on Android with the same settings. I build my app with build.phonegap.com, maybe i need to change something in my config.xml. Any idea?
![xml](https://user-images.githubusercontent.com/6918514/30420759-e389f2e2-993a-11e7-9d65-5b414e9c28f0.PNG)

**Comment by becvert** [comment]
@Filavision It looks like there had been 89 ad requests so the mediation must be working.
If you don't have impressions it's not because of the plugin.
try an average eCPM $1 and "CPM und Fullrate ausgelichen" maybe

**Comment by PixelnomadsLtd** [comment]
I tried already all kinds of settings with $1 and $1000 eCPM and different fill options. Nothing worked in my case...

**Comment by mattlin4567** [comment]
@becvert which Admob plugin do you use?

**Comment by becvert** [comment]
cordova-plugin-admob-free

I would go in productionif I were you. so with much more ad requests you may see impressions at last.
and it won't hurt as if it doesn't work you still have the google ads.

**Comment by mattlin4567** [comment]
![default](https://user-images.githubusercontent.com/7845567/34050863-6785ef74-e1f7-11e7-972d-ea9e88f6690e.PNG)
finally got this work recently,  but the weird is it only work on iOS
I have newest cordova-plugin-admob-free installed 
did I miss anything?
---------180125---------
both platforms work now.
few points should be noticed:
1. need to install and login in Facebook on the device
2. set the FB's eCPM higher than Admob in the meditation page, to sure the request will send first
3. after above steps, you can check the debugger in FB application dashboard, if you don't see any requests, check above steps again
