### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by lucaele** [becvert/cordova-plugin-admob-mediation-facebook#5]
Hi all,
this plugin make an error on build Android:

Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

cordova: 7.1.0

**and this plugins list:**
cordova-admob-sdk 0.17.0 "AdMob SDK"
cordova-plugin-admob-free 0.17.4 "Cordova AdMob Plugin"
cordova-plugin-cocoapod-support 1.6.0 "Cordova CocoaPods Dependency Support"
cordova-plugin-facebook4 2.3.0 "Facebook Connect"
cordova-plugin-firebase 1.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-promise-polyfill 0.0.2 "cordova-promise-polyfill"
cordova-support-google-services 1.2.1 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"

Any idea?
Thanks

**Comment by becvert** [comment]
try to install https://github.com/podtrackers/cordova-multidex
